# Generated by Django 3.0.6 on 2020-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_auto_20200611_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
