# Generated by Django 3.0.6 on 2020-06-12 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
