# Generated by Django 3.0.6 on 2020-06-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_task_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author',
        ),
    ]
